### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by nelsam** [eddykaya/keycloak-custom-required-action#1]
I have a use case for something sort of like this, but without a LICENSE[.md] file, I don't know how I'm allowed to use it.  I was planning to copy what I needed to a different repo (and provide attribution) but this repo needs a license first.

**Comment by edwinrolle** [comment]
Hey @nelsam ,

I just added a MIT license file to the repository, see:
https://github.com/eddykaya/keycloak-custom-required-action/blob/master/LICENSE

Is this sufficient for you?

**Comment by nelsam** [comment]
@eddykaya Yep, that works.  Thanks!
